feat(apm): add prometheus metrics support
axonweb3/axon pull request #100
Opened 2022-02-13 11:39 UTC by zhengjianhui

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

2022-02-13 12:11 UTC, KaoImin commented on common/apm/src/prom_server.rs
> +    axum::Router::new().route("/metrics", axum::routing::get(get_metrics))
```suggestion
    Router::new().route("/metrics", axum::routing::get(get_metrics))
```

2022-02-13 15:23 UTC, KaoImin requested changes

2022-02-13 15:23 UTC, KaoImin commented on common/apm/src/lib.rs
>  pub use muta_apm;
Rename the module and delete the blank line above.

2022-02-13 15:23 UTC, KaoImin commented on common/apm/src/metrics/api.rs
> +#![allow(non_snake_case)]
Add a blank line below.

2022-02-13 15:23 UTC, KaoImin commented on common/apm/src/prom_server.rs
> +    Router::new().route("/metrics", axum::routing::get(get_metrics))
```suggestion
    Router::new().route("/metrics", routing::get(get_metrics))
```

2022-02-13 15:23 UTC, KaoImin commented on common/apm/src/prom_server.rs
> +    let metrics_data = match super::metrics::all_metrics() {
Call this function from `crate` rather than from `super`.

2022-02-13 15:23 UTC, KaoImin commented on core/run/src/lib.rs
> +        // Start http server
```suggestion
        // Start prometheus http server
```

2022-02-13 15:23 UTC, KaoImin commented on core/run/src/lib.rs
> +            let addr = std::net::SocketAddr::from(([127, 0, 0, 1], 8100));
Read the address from the config file.

2022-02-13 15:23 UTC, KaoImin commented on core/run/src/lib.rs
> +                .unwrap();
Extract into a `run_prometheus_server(addr)` function.

2022-02-14 08:56 UTC, KaoImin commented on common/apm/src/server.rs
> +use std::net::SocketAddr;
See this lint https://github.com/cryptape/axon-internal/wiki/Axon-Develop-Lint#order-of-import

2022-02-14 09:00 UTC, KaoImin commented on core/run/src/lib.rs
> +            common_apm::server::run_prometheus_server(prometheus_listening_address);
use common_apm::server::run_prometheus_server;

2022-02-15 08:13 UTC, KaoImin approved these changes

2022-02-15 08:24 UTC, driftluo approved these changes

2022-02-15 08:34 UTC, merged