feat(executor): add ckb light client system contract
axonweb3/axon pull request #1068
Opened 2023-03-13 04:38 UTC by peterzhb

**What this PR does / why we need it**:

This PR adds ckb light client on Axon to support cross chain functionalities.

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

NIL

**CI Description**

| CI Name                                   | Description                                                     |
| ----------------------------------------- | --------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition    |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`      |
| *Coverage Test*                           | Get the unit test coverage report                             |
| *E2E Test*                                | Run end-to-end test to check interfaces                         |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`     |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                               |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3             |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin           |

**CI Usage**

> Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] Chaos CI
- [x] Cargo Clippy
- [ ] Coverage Test
- [ ] E2E Tests
- [x] Code Format
- [x] Unit Tests
- [ ] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

2023-03-13 14:22 UTC, KaoImin requested changes

2023-03-13 14:22 UTC, KaoImin commented on core/executor/src/system_contract/ckb_light_client/abi/mod.rs
> +use ckb_types::prelude::*;
```suggestion
use ckb_types::{packed, prelude::*};
```

2023-03-13 14:22 UTC, KaoImin commented on core/executor/src/system_contract/ckb_light_client/mod.rs
> +            _ => unreachable!(),
The `unreachable!()` here is insidious. If the input data is invalid, it will cause the program panic.

2023-03-13 14:22 UTC, KaoImin commented on core/executor/src/system_contract/mod.rs
> +use protocol::types::{Bytes, Hasher, SignedTransaction, TxResp, H160, H256};
It is out of order.

2023-03-13 14:22 UTC, KaoImin commented on core/executor/src/system_contract/mod.rs
> +pub use crate::system_contract::native_token::NativeTokenContract;
The position is incorrect.

2023-03-13 14:22 UTC, KaoImin commented on core/executor/src/system_contract/ckb_light_client/store.rs
> +    pub fn get_header(&self, block_hash: &H256) -> ProtocolResult<Option<packed::Header>> {
```suggestion
    pub fn get_header(&self, block_hash: &[u8]) -> ProtocolResult<Option<packed::Header>> {
```

2023-03-13 14:22 UTC, KaoImin commented on core/executor/src/system_contract/ckb_light_client/mod.rs
> +    pub fn get_header(&self, block_hash: &H256) -> ProtocolResult<Option<packed::Header>> {
```suggestion
    pub fn get_header(&self, block_hash: &[u8]) -> ProtocolResult<Option<packed::Header>> {
```

2023-03-13 14:22 UTC, KaoImin commented on core/executor/src/system_contract/ckb_light_client/handle.rs
> +}
This file seems useless.

2023-03-14 01:57 UTC, felicityin commented on core/executor/src/system_contract/ckb_light_client/contract/contracts/CkbLightClient.sol
> +    function update(Header calldata header) public view {}
```suggestion
function update(Header[] calldata headers) public view {}
```

2023-03-14 01:58 UTC, felicityin commented on core/executor/src/system_contract/ckb_light_client/contract/contracts/CkbLightClient.sol
> +    function rollback(bytes32 blockHash) public view {}
```suggestion
function rollback(bytes32[] blockHashs) public view {}
```

2023-03-14 02:02 UTC, felicityin commented on core/executor/src/system_contract/image_cell/abi/image_cell_abi.json
> +]
A line is missing at the end of the file.

2023-03-14 02:02 UTC, felicityin commented on core/executor/src/system_contract/image_cell/contract/yarn.lock
> +  integrity sha512-rVksvsnNCdJ/ohGc6xgPwyN8eheCxsiLM8mxuE/t/mOVqJewPuO1miLpTHQiRgTKCLexL4MeAFVagts7HmNZ2Q==
A line is missing at the end of the file.

2023-03-14 07:25 UTC, felicityin commented on core/executor/src/system_contract/ckb_light_client/contract/contracts/CkbLightClient.sol
> +    function update(Header calldata header) public view {}
The contract should receive a group of headers at one time.

2023-03-14 15:11 UTC, KaoImin approved these changes, later dismissed

2023-03-14 15:12 UTC, KaoImin commented
The branch should be rebase on the top of main branch before merge.

2023-03-15 02:27 UTC, felicityin commented
Missing solidity files.

2023-03-15 09:27 UTC, peterzhb commented
> Missing solidity files.

It will be put in another pr as it is suggested to put all the system contracts' hardhat projects into one under builtin-contract folder.

2023-03-15 09:28 UTC, KaoImin commented
/run-ci

2023-03-15 09:28 UTC, KaoImin commented
/run-ci

2023-03-15 11:42 UTC, KaoImin commented on core/network/src/service.rs
Do not remove this import, it is used in Linux platform.

2023-03-15 12:18 UTC, KaoImin commented
/run-ci

2023-03-15 12:49 UTC, KaoImin approved these changes

2023-03-15 12:50 UTC, merged