refactor(core): refactor axon start
axonweb3/axon pull request #1116
Opened 2023-03-29 06:44 UTC by peterzhb

**What this PR does / why we need it**:

This PR refactors the axon start function to multiple function blocks.

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

NIL

**CI Description**

| CI Name                                   | Description                                                     |
| ----------------------------------------- | --------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition    |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`      |
| *Coverage Test*                           | Get the unit test coverage report                             |
| *E2E Test*                                | Run end-to-end test to check interfaces                         |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`     |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                               |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3             |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin           |

**CI Usage**

> Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] Chaos CI
- [x] Cargo Clippy
- [ ] Coverage Test
- [x] E2E Tests
- [x] Code Format
- [x] Unit Tests
- [x] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

2023-04-11 15:43 UTC, peterzhb commented
/run-ci

2023-04-12 01:42 UTC, KaoImin requested changes

2023-04-12 01:42 UTC, KaoImin commented on devtools/chain/config.toml
> +multi_address = "/ip4/172.17.0.1/tcp/10000/p2p/QmNk6bBwkLPuqnsrtxpp819XLZY3ymgjs3p1nKtxBVgqxj"
Rollback this

2023-04-12 01:42 UTC, KaoImin commented on devtools/chain/genesis_single_node.json
Why change genesis?

2023-04-12 05:03 UTC, peterzhb commented on devtools/chain/genesis_single_node.json
probably due to rebase issue

2023-04-13 04:35 UTC, peterzhb commented
/run-ci

2023-04-17 02:53 UTC, driftluo submitted a review, later dismissed

2023-04-17 02:54 UTC, KaoImin commented
Please rebase the main branch @peterzhb

2023-04-17 09:18 UTC, KaoImin submitted a review, later dismissed

2023-04-17 09:19 UTC, KaoImin commented
/run-ci

2023-04-17 09:46 UTC, peterzhb commented
/run-ci

2023-04-17 13:47 UTC, KaoImin approved these changes

2023-04-17 13:48 UTC, merged