refactor: change config to single struct
axonweb3/axon pull request #1328
Opened 2023-08-16 08:20 UTC by driftluo

**What this PR does / why we need it**:

This PR change metadata config to single struct

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

NIL

**CI Description**

| CI Name                                   | Description                                                     |
| ----------------------------------------- | --------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition    |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`      |
| *Coverage Test*                           | Get the unit test coverage report                             |
| *E2E Test*                                | Run end-to-end test to check interfaces                         |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`     |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                               |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3             |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin           |

**CI Usage**

> Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] Chaos CI
- [ ] Cargo Clippy
- [ ] Coverage Test
- [ ] E2E Tests
- [ ] Code Format
- [ ] Unit Tests
- [ ] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

2023-08-16 09:41 UTC, chaoticlonghair commented on core/run/src/tests.rs
> +    "0x47bd35cdb8bd43da1d5ce85ad77fd68de4d654fc2677ac36bd3e18cfda0ff136";
Mark this PR as a break change in PR description.

2023-08-16 16:14 UTC, Flouse commented on core/run/src/tests.rs
> +    "0x47bd35cdb8bd43da1d5ce85ad77fd68de4d654fc2677ac36bd3e18cfda0ff136";
+1

2023-08-21 02:52 UTC, Flouse commented
/run-ci

2023-08-21 02:53 UTC, Flouse requested changes
Please rebase main branch to resolve the conflicts.

And run CI again, thanks.

2023-08-21 07:19 UTC, driftluo commented
/run-ci

2023-08-21 07:48 UTC, driftluo commented
/run-ci

2023-08-22 02:00 UTC, driftluo commented
/run-ci

2023-08-23 07:48 UTC, KaoImin commented
/run-ci

2023-08-23 07:55 UTC, KaoImin approved these changes

2023-08-23 09:19 UTC, chaoticlonghair approved these changes
I didn't understand the implementation details of this feature clearly.

Since there is no obvious issue in coding, let's merge it to avoid blocking the following part; then we can test the feature later.

2023-08-23 09:23 UTC, Flouse approved these changes

2023-08-23 09:23 UTC, merged