ci: add health-check shell script
axonweb3/axon pull request #1432
Opened 2023-09-14 09:44 UTC by Simon-Tl

## What this PR does / why we need it?

Add the health check script to confirm the status after startup more quickly

### What is the impact of this PR?

No Breaking Change

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] E2E Tests
- [ ] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`                     |
| *Coverage Test*                           | Get the unit test coverage report                                         |
| *E2E Test*                                | Run end-to-end test to check interfaces                                   |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`           |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

2023-09-14 14:28 UTC, Flouse commented on devtools/ci/scripts/health_check.sh
> +#!/bin/bash
It's better to put this script into `devtools/docker` dir.

2023-09-14 14:31 UTC, Flouse requested changes

2023-09-14 14:31 UTC, Flouse commented on devtools/ci/scripts/health_check.sh
> +
```suggestion
```

2023-09-14 14:31 UTC, Flouse commented on devtools/ci/scripts/health_check.sh
> +block_stats
```suggestion
block_stats

```

2023-09-15 04:53 UTC, Simon-Tl commented on devtools/ci/scripts/health_check.sh
> +#!/bin/bash
ok, let me revise it.

2023-09-15 15:13 UTC, Flouse approved these changes

2023-09-17 23:35 UTC, jiangxianliang007 approved these changes

2023-09-18 08:35 UTC, merged