feat: change serialization method for extra_data
axonweb3/axon pull request #1442
Opened 2023-09-20 10:26 UTC by driftluo

## What this PR does / why we need it?

This PR modified the serialization method of extra_data, fixed index 0 to be occupied by hardfork, and retained the possibility of using other data in the future

### What is the impact of this PR?

No Breaking Change

**PR relation**:
- Ref #

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] E2E Tests
- [ ] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

### **CI Description**

| CI Name                                   | Description                                                               |
| ----------------------------------------- | ------------------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`                     |
| *Coverage Test*                           | Get the unit test coverage report                                         |
| *E2E Test*                                | Run end-to-end test to check interfaces                                   |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`           |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                                       |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3                        |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin                      |

</details>

2023-09-20 14:23 UTC, Flouse requested changes, later dismissed
https://github.com/axonweb3/axon/actions/runs/6247286176/job/16959879364#step:4:873
The multi-nodes test failed.

## These are the logs of 4 nodes

[multi-axon-nodes-logs.zip](https://github.com/axonweb3/axon/files/12674224/multi-axon-nodes-logs.zip)

2023-09-20 15:00 UTC, Flouse commented on protocol/src/types/block.rs
> +    pub extra_data:               Vec<ExtraData>,
```suggestion
    /// Extra data for the block header
    /// The first index of extra_data is used to store hardfork information: `HardforkInfoInner`
    pub extra_data:               Vec<ExtraData>,
```

2023-09-21 00:44 UTC, chaoticlonghair commented on core/consensus/src/engine.rs
> +            if let Ok(data) = HardforkInfoInner::decode(&t.inner) {
Throw errors when bytes is not empty but decode failed.

Dirty data in extra data is not allowed.

2023-09-21 01:39 UTC, Flouse commented
# Test on a single Axon node
```bash
// Request
curl -X POST https://special-trout-xrw6p77gjf6q7g-8000.app.github.dev/ \
  --header 'Content-Type: application/json' \
  --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x2", true],"id":1}'
```

### Block 0
```json
{"jsonrpc":"2.0","result":{"hash":"0xc4723396dab95f64aca4a808e29aa4fbb9d7ca113b561dbaf5dc2df7bb4a72e9","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","author":"0x0000000000000000000000000000000000000000","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0x601bd874d41eb9adb32021ee3ab934e0481065c58abfe7e757e33fb01be18dd5","transactionsRoot":"0x0000000000000000000000000000000000000000000000000000000000000000","receiptsRoot":"0x8544b530238201f1620b139861a6841040b37f78f8bdae8736ef5cec474e979b","number":"0x0","gasUsed":"0x0","gasLimit":"0x0",
"extraData":["0xa3e280a00000000000000000000000000000000000000000000000000000000000000000"],
"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","timestamp":"0x641d844f","difficulty":"0x1","totalDifficulty":"0x0","sealFields":[],"baseFeePerGas":"0x539","uncles":[],"transactions":[{"type":"0x2","blockNumber":"0x0","blockHash":"0xc4723396dab95f64aca4a808e29aa4fbb9d7ca113b561dbaf5dc2df7bb4a72e9","hash":"0x5fbdb316eb4788e30ec62cbb5f60e2cf79a7a5162018af715187376e7ff448af","nonce":"0x0","transactionIndex":"0x0","from":"0x8ab0cf264df99d83525e9e11c7e4db01558ae1b1","to":null,"value":"0x0","gas":"0x1c9c380","gasPrice":"0x539","maxFeePerGas":"0x539","maxPriorityFeePerGas":"0x539","raw":"0x02f930a08441786f6e80820539808401c9c3808080b9304860806040523480156200001157600080fd5b5060405162002f6838038062002f6883398181016040528101906200003791906200044f565b828281600390805190602001906200005192919062000316565b5080600490805190602001906200006a92919062000316565b5050506200008d62000081620000d560201b60201c565b620000dd60201b60201c565b620000b16000801b620000a5620000d560201b60201c565b620001a360201b60201c565b80600660146101000a81548160ff021916908360ff1602179055505050506200066e565b600033905090565b6000600660009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16905081600660006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055508173ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff167f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e060405160405180910390a35050565b620001b58282620001b960201b60201c565b5050565b620001cb8282620002ab60201b60201c565b620002a75760016005600084815260200190815260200160002060000160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060006101000a81548160ff0219169083151502179055506200024c620000d560201b60201c565b73ffffffffffffffffffffffffffffffffffffffff168173ffffffffffffffffffffffffffffffffffffffff16837f2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d60405160405180910390a45b5050565b60006005600084815260200190815260200160002060000160008373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200190815260200160002060009054906101000a900460ff16905092915050565b828054620003249062000579565b90600052602060002090601f01602090048101928262000348576000855562000394565b82601f106200036357805160ff191683800117855562000394565b8280016001018555821562000394579182015b828111156200039357825182559160200191906001019062000376565b5b509050620003a39190620003a7565b5090565b5b80821115620003c2576000816000905550600101620003a8565b5090565b6000620003dd620003d78462000500565b620004d7565b905082815260208101848484011115620003f657600080fd5b6200040384828562000543565b509392505050565b600082601f8301126200041d57600080fd5b81516200042f848260208601620003c6565b91505092915050565b600081519050620004498162000654565b92915050565b6000806000606084860312156200046557600080fd5b600084015167ffffffffffffffff8111156200048057600080fd5b6200048e868287016200040b565b935050602084015167ffffffffffffffff811115620004ac57600080fd5b620004ba868287016200040b565b9250506040620004cd8682870162000438565b9150509250925092565b6000620004e3620004f6565b9050620004f18282620005af565b919050565b6000604051905090565b600067ffffffffffffffff8211156200051e576200051d62000614565b5b620005298262000643565b9050602081019050919050565b600060ff82169050919050565b60005b838110156200056357808201518184015260208101905062000546565b8381111562000573576000848401525b50505050565b600060028204905060018216806200059257607f821691505b60208210811415620005a957620005a8620005e5565b5b50919050565b620005ba8262000643565b810181811067ffffffffffffffff82111715620005dc57620005db62000614565b5b80604052505050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052602260045260246000fd5b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b6000601f19601f8301169050919050565b6200065f8162000536565b81146200066b57600080fd5b50565b6128ea806200067e6000396000f3fe608060405234801561001057600080fd5b50600436106101585760003560e01c8063715018a6116100c3578063a457c2d71161007c578063a457c2d7146103db578063a9059cbb1461040b578063d547741f1461043b578063dd62ed3e14610457578063ec87621c14610487578063f2fde38b146104a557610158565b8063715018a61461032b5780638da5cb5b1461033557806391d148541461035357806395d89b41146103835780639dc29fac146103a1578063a217fddf146103bd57610158565b80632f2ff15d116101155780632f2ff15d14610259578063313ce5671461027557806336568abe1461029357806339509351146102af57806340c10f19146102df57806370a08231146102fb57610158565b806301ffc9a71461015d57806306fdde031461018d578063095ea7b3146101ab57806318160ddd146101db57806323b872dd146101f9578063248a9ca314610229575b600080fd5b61017760048036038101906101729190611c07565b6104c1565b6040516101849190611f6a565b60405180910390f35b61019561053b565b6040516101a29190611fa0565b60405180910390f35b6101c560048036038101906101c09190611b66565b6105cd565b6040516101d29190611f6a565b60405180910390f35b6101e36105f0565b6040516101f09190612182565b60405180910390f35b610213600480360381019061020e9190611b17565b6105fa565b6040516102209190611f6a565b60405180910390f35b610243600480360381019061023e9190611ba2565b610629565b6040516102509190611f85565b60405180910390f35b610273600480360381019061026e9190611bcb565b610649565b005b61027d61066a565b60405161028a919061219d565b60405180910390f35b6102ad60048036038101906102a89190611bcb565b610681565b005b6102c960048036038101906102c49190611b66565b610704565b6040516102d69190611f6a565b60405180910390f35b6102f960048036038101906102f49190611b66565b61073b565b005b61031560048036038101906103109190611ab2565b610774565b6040516103229190612182565b60405180910390f35b6103336107bc565b005b61033d6107d0565b60405161034a9190611f4f565b60405180910390f35b61036d60048036038101906103689190611bcb565b6107fa565b60405161037a9190611f6a565b60405180910390f35b61038b610865565b6040516103989190611fa0565b60405180910390f35b6103bb60048036038101906103b69190611b66565b6108f7565b005b6103c5610930565b6040516103d29190611f85565b60405180910390f35b6103f560048036038101906103f09190611b66565b610937565b6040516104029190611f6a565b60405180910390f35b61042560048036038101906104209190611b66565b6109ae565b6040516104329190611f6a565b60405180910390f35b61045560048036038101906104509190611bcb565b6109d1565b005b610471600480360381019061046c9190611adb565b6109f2565b60405161047e9190612182565b60405180910390f35b61048f610a79565b60405161049c9190611f85565b60405180910390f35b6104bf60048036038101906104ba9190611ab2565b610a9d565b005b60007f7965db0b00000000000000000000000000000000000000000000000000000000 [...]

2023-09-21 02:08 UTC, chaoticlonghair approved these changes

2023-09-21 06:56 UTC, KaoImin approved these changes

2023-09-21 07:28 UTC, merged