chore: bump some crates version
axonweb3/axon pull request #1623
Opened 2023-12-06 07:17 UTC by KaoImin

## What this PR does / why we need it?

This PR bump some crates version.

### What is the impact of this PR?

No Breaking Change

**PR relation**:
- Ref #

<details><summary>CI Settings</summary><br/>

### **CI Usage**

**Tip**: Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] Web3 Compatible Tests
- [ ] OpenZeppelin tests
- [ ] v3 Core Tests

### **CI Description**

| CI Name                | Description                                                                                             |
| ---------------------- | ------------------------------------------------------------------------------------------------------- |
| *Web3 Compatible Test* | Test the Web3 compatibility of Axon                                                                     |
| *v3 Core Test*         | Run the compatibility tests provided by Uniswap V3                                                      |
| *OpenZeppelin tests*   | Run the compatibility tests provided by OpenZeppelin, including OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19 |
</details>

2023-12-06 07:24 UTC, KaoImin commented
/run-ci

2023-12-06 07:24 UTC, yangby-cryptape submitted a review, later dismissed

2023-12-06 07:25 UTC, driftluo approved these changes, later dismissed

2023-12-06 07:42 UTC, Flouse approved these changes

2023-12-06 07:44 UTC, Flouse requested changes
https://github.com/axonweb3/axon/actions/runs/7111401266/job/19359413824?pr=1623#step:4:392
`Building Axon` was failed.

2023-12-06 08:46 UTC, yangby-cryptape approved these changes

2023-12-06 08:50 UTC, sunchengzhu approved these changes

2023-12-06 08:58 UTC, KaoImin commented
/run-ci

2023-12-07 02:03 UTC, Flouse approved these changes

2023-12-07 02:20 UTC, merged