fix(executor): deduct gas before execute transaction
axonweb3/axon pull request #512
Opened 2022-07-14 09:36 UTC by KaoImin

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

### CI Switch

ci-runs-only: [Chaos CI, Cargo Clippy, Coverage Test, E2E Tests, Code Format, Unit Tests]

2022-07-14 10:49 UTC, mohanson commented on core/executor/src/lib.rs
> +            GAS_CREATE_TRANSACTION + data_gas_cost(&data)
GAS_CREATE_TRANSACTION should be 21000 + 32000

2022-07-14 10:52 UTC, mohanson requested changes
GAS_CREATE_TRANSACTION should be 21000 + 32000

2022-07-14 13:56 UTC, mohanson approved these changes, later dismissed

2022-07-15 08:57 UTC, driftluo approved these changes

2022-07-15 08:57 UTC, merged