[WIP] feat(ibc): add tendermint rpc service
axonweb3/axon pull request #735
Opened 2022-09-23 15:08 UTC by ImJeremyHe

**What this PR does / why we need it**:

This PR

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

NIL

**CI Description**

| CI Name                                   | Description                                                     |
| ----------------------------------------- | --------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition    |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`      |
| *Coverage Test*                           | Get the unit test coverage report                             |
| *E2E Test*                                | Run end-to-end test to check interfaces                         |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`     |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                               |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3             |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin           |

**CI Usage**

> Check the CI you want to run below, and then comment `\run-ci`.

**CI Switch**

- [ ] Chaos CI
- [x] Cargo Clippy
- [ ] Coverage Test
- [x] E2E Tests
- [x] Code Format
- [x] Unit Tests
- [ ] Web3 Compatible Tests
- [x] OCT 1-5 And 12-15
- [x] OCT 6-10
- [x] OCT 11
- [x] OCT 16-19
- [x] v3 Core Tests

2022-09-24 04:53 UTC, ImJeremyHe commented
/run-ci

2022-09-25 00:52 UTC, ImJeremyHe commented
/run-ci

2022-09-25 04:26 UTC, ImJeremyHe commented
/run-ci

2022-09-25 07:01 UTC, KaoImin requested changes

2022-09-25 07:01 UTC, KaoImin commented on common/config-parser/src/types.rs
> +    pub tmrpc: String,
What is the meaning of `tmrpc`?

2022-09-25 07:01 UTC, KaoImin commented on core/ibc/Cargo.toml
> +creep = "0.2"
`creep::Context` is re-export from `protocol::traits::Context`.

2022-09-25 07:01 UTC, KaoImin commented on core/ibc/Cargo.toml
> +tokio = { version = "1.20", features = ["full"] }
`tokio` is re-export from `protocol::tokio`.

2022-09-25 07:01 UTC, KaoImin commented on core/ibc/src/tmrpc/mod.rs
> +pub struct TendermintRpcImpl<S: Storage> {
This should rename as `TendermintRpcAdapter`.

2022-09-25 09:32 UTC, ImJeremyHe commented on common/config-parser/src/types.rs
> +    pub tmrpc: String,
tendermint rpc
https://docs.tendermint.com/main/rpc/#/Info/tx_search

2022-09-25 10:11 UTC, ImJeremyHe commented
/run-ci

2022-09-26 02:01 UTC, KaoImin commented
Please bump the version of `tendermint` to v0.25.

2022-10-07 03:44 UTC, KaoImin commented
Refactor the rpc server imply as #750 does. The tendermint rpc should be in `core/api/jsonrpc`.

2022-10-25 06:11 UTC, closed without merging