feat: gasless feature
axonweb3/axon pull request #960
Opened 2023-01-04 01:12 UTC by wenyuanhust

**What this PR does / why we need it**:

This PR

**Which issue(s) this PR fixes**:

Fixes #

**Which docs this PR relation**:

Ref #

**Which toolchain this PR adaption**:

No Breaking Change

**Special notes for your reviewer**:

NIL

**CI Description**

| CI Name                                   | Description                                                     |
| ----------------------------------------- | --------------------------------------------------------------- |
| *Chaos CI*                                | Test the liveness and robustness of Axon under terrible network condition    |
| *Cargo Clippy*                            | Run `cargo clippy --all --all-targets --all-features`      |
| *Coverage Test*                           | Get the unit test coverage report                             |
| *E2E Test*                                | Run end-to-end test to check interfaces                         |
| *Code Format*                             | Run `cargo +nightly fmt --all -- --check` and `cargo sort -gwc`     |
| *Web3 Compatible Test*                    | Test the Web3 compatibility of Axon                               |
| *v3 Core Test*                            | Run the compatibility tests provided by Uniswap V3             |
| *OCT 1-5 \| 6-10 \| 11 \| 12-15 \| 16-19* | Run the compatibility tests provided by OpenZeppelin           |

**CI Usage**

> Check the CI you want to run below, and then comment `/run-ci`.

**CI Switch**

- [ ] Chaos CI
- [ ] Cargo Clippy
- [ ] Coverage Test
- [ ] E2E Tests
- [ ] Code Format
- [ ] Unit Tests
- [ ] Web3 Compatible Tests
- [ ] OCT 1-5 And 12-15
- [ ] OCT 6-10
- [ ] OCT 11
- [ ] OCT 16-19
- [ ] v3 Core Tests

2023-03-21 03:50 UTC, liya2017 requested changes

2023-03-21 03:50 UTC, liya2017 commented on core/executor/src/system_contract/gasless/contract/contracts/Sample.sol
> +}
```suggestion
}

```

2023-03-21 03:50 UTC, liya2017 commented on core/executor/src/system_contract/gasless/contract/contracts/SponsorWhitelistControl.sol
> +}
```suggestion
}

```

2023-03-21 03:50 UTC, liya2017 commented on core/executor/src/system_contract/gasless/contract/test/SponsorWhitelistControl.js
> +});
```suggestion
});

```

2023-03-22 07:19 UTC, hongda3141 approved these changes

2023-04-04 04:15 UTC, closed without merging